apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: entitled-anteater-nodejs
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:f8badb972ab27458b944cd9226cc23d2ace9b8f1@sha256:76ef0a13734eafb2f692a7e43fea93ccb74bf7835dd85ca8e650c1c925324819
        name: container-image  
