apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: entitled-anteater-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: entitled-anteater-nodejs 
  name: entitled-anteater-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: entitled-anteater-nodejs 
